server:
  port: 9090
  servlet:
    context-path: /security
#spring:
#  security:
#    user:
#      name: 'admin'
#      password: 'admin'
spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tutorial?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true